### ISSUE TITLE
Publish to pub.dartlang.org

### ISSUE THREAD

**Issue by jeffreyyoung** [cloudwebrtc/flutter-webrtc#10]
I notice this package is not published to pub.dartlang.org.

Is there a reason it hasn't been published?

thanks!

**Comment by cloudwebrtc** [comment]
Thank you for reminding us that we will upload the plug-in to pub.dartlang.org as soon as possible.

**Comment by cloudwebrtc** [comment]
@jeffreyyoung The package has been published to https://pub.dartlang.org/packages/flutter_webrtc, and you can try adding flutter_webrtc to your flutter project dependency.

**Comment by jeffreyyoung** [comment]
awesome I'll try it out! thanks!
