### ISSUE TITLE
Lower minSdk version to 16 for Android

### ISSUE THREAD

**Issue by njovy** [cloudwebrtc/flutter-webrtc#103]
Is it possible to lower minSdk version to 16?

**Comment by cloudwebrtc** [comment]
The minimum SDK version we tested was 18,  you can modify android/build.gradle and example/android/app/build.gradle to change minSdkVersion to 16.

**Comment by njovy** [comment]
@cloudwebrtc Yes that's what I am doing but can this be applied to the master?

**Comment by cloudwebrtc** [comment]
@njovy If using API level 16-17 to test on a real device is okay, I'd be happy to accept PR to master.

**Comment by rostopira** [comment]
Actually, I've set minimum 18, because of video recording feature, it will definitely crash on lower API
Also, WebRTC team will drop support of <19 (as well as Chrome) soon

**Comment by njovy** [comment]
@rostopira Okay I guess I will have to maintain my own repo as I don't use recording feature. Thank you for your response.
