### ISSUE TITLE
[Android] Local Stream is disposing on peerconnection.close()  ? 

### ISSUE THREAD

**Issue by GuillaumeJulien** [cloudwebrtc/flutter-webrtc#106]
I try to do multipeer connection with MediaStream I use a [provider](https://pub.dev/packages/provider) to inject my local stream in my peer connection, but when I close one peer connection when someone leave, the local stream was cut. 
What i'm doing wrong ? 
That working well on iOS contrariwise =/

**Comment by cloudwebrtc** [comment]
@GuillaumeJulien Is the problem only on Android? I think it is a bug, if it is, I think you can find the reason through android logcat.

**Comment by GuillaumeJulien** [comment]
I tryed with the [webrtc-demo ](https://github.com/cloudwebrtc/flutter-webrtc-demo/) 
I just add Methode in Signaling Class:

`closePeers(){
    _peerConnections.forEach((key, pc) {
      pc.close();
    });
  }`

and when i close peerconnection I have this error, and camera still stuck (on OnePlus pro) :  

`I/org.webrtc.Logging(21515): WebRtcAudioRecordExternal: stopRecording
I/org.webrtc.Logging(21515): WebRtcAudioRecordExternal: stopThread
I/org.webrtc.Logging(21515): WebRtcAudioEffectsExternal: release
I/org.webrtc.Logging(21515): WebRtcAudioRecordExternal: releaseAudioResources
I/org.webrtc.Logging(21515): HardwareVideoEncoder: Releasing MediaCodec on output thread
I/MediaCodec(21515): stop
I/org.webrtc.Logging(21515): HardwareVideoEncoder: Release on output thread done
I/org.webrtc.Logging(21515): GlShader: Deleting shader.
I/org.webrtc.Logging(21515): AndroidVideoDecoder: release
I/org.webrtc.Logging(21515): AndroidVideoDecoder: Releasing MediaCodec on output thread
I/MediaCodec(21515): stop
D/SurfaceUtils(21515): disconnecting from surface 0x7127789010, reason disconnectFromSurface
I/org.webrtc.Logging(21515): AndroidVideoDecoder: Release on output thread done
I/org.webrtc.Logging(21515): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging(21515): SurfaceTextureHelper: dispose()
I/org.webrtc.Logging(21515): VolumeLogger: stop@[name=worker_thread - 21561, id=1760]
I/org.webrtc.Logging(21515): WebRtcAudioTrackExternal: stopPlayout
I/org.webrtc.Logging(21515): WebRtcAudioTrackExternal: underrun count: 1
I/org.webrtc.Logging(21515): WebRtcAudioTrackExternal: stopThread
I/org.webrtc.Logging(21515): WebRtcAudioTrackExternal: Stopping the AudioTrackThread...
I/org.webrtc.Logging(21515): WebRtcAudioTrackExternal: Calling AudioTrack.stop...
I/android.media.AudioTrack(21515): stop() packageName: com.cloudwebrtc.flutterwebrtcdemomSampleRate: 48000
D/AudioTrack(21515): stop() called with 560160 frames delivered
I/org.webrtc.Logging(21515): WebRtcAudioTrackExternal: AudioTrack.stop is done.
I/org.webrtc.Logging(21515): WebRtcAudioTrackExternal: AudioTrackThread has now been stopped.
I/org.webrtc.Logging(21515): WebRtcAudioTrackExternal: releaseAudioResources
I/android.media.AudioTrack(21515): stop() packageName: com.cloudwebrtc.flutterwebrtcdemomSampleRate: 48000
I/org.webrtc.Logging(21515): NetworkMonitor: Stop monitoring with native observer 486025250368
I/org.webrtc.Logging(21515): NetworkMonitorAutoDetect: Unregister network callback
I/org.webrtc.Logging(21515): NetworkMonitorAutoDetect: Unregister network callback
D/OnePlusJankManager(21515):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = com.cloudwebrtc.flutterwebrtcdemo/com.cloudwebrtc.flutterwebrtcdemo.MainActivity--- jank level = 2
I/org.webrtc.Logging(21515): EglRenderer: Duration: 4003 ms. Frames received: 117. Dropped: 0. Rendered: 117. Render fps: 29,2. Average render time: 2000 us. Average swapBuffer time: 1061 us.
I/org.webrtc.Logging(21515): CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging(21515): EglRenderer: Duration: 4004 ms. Frames received: 103. Dropped: 0. Rendered: 103. Render fps: 25,7. Average render time: 2120 us. Average swapBuffer time: 1030 us.
I/org.webrtc.Logging(21515): CameraStatistics: Camera fps: 30.
`

**Comment by GuillaumeJulien** [comment]
imo its due to this dispose, https://github.com/cloudwebrtc/flutter-webrtc/blob/4e2548b39167f04a6eda95bb9bb0679710ef12be/android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java#L82 

https://stackoverflow.com/questions/44261220/random-native-crash-in-webrtc-peerconnection-while-disconnecting

maybe we can split the close function in two part, dispose (call for the end of call) and close (for others) ?
