### ISSUE TITLE
Make captureFrame also return byte buffer to image data

### ISSUE THREAD

**Issue by JACKSONMEISTER** [cloudwebrtc/flutter-webrtc#108]
I need to retrieve a byte buffer to the current frame for further image processing while in a WebRTC session.

**Comment by cloudwebrtc** [comment]
You can intercept video RAW data at 
https://github.com/cloudwebrtc/flutter-webrtc/blob/master/ios/Classes/FlutterRTCVideoRenderer.m#L174
and 
https://github.com/cloudwebrtc/flutter-webrtc/blob/master/android/src/main/java/com/cloudwebrtc/webrtc/SurfaceTextureRenderer.java#L97
. Maybe you can use the Texture's EventChannel to call back the data to the dart layer. I think it will be more difficult to pass back to the native layer because of dart<->native messages. Is asynchronous.

**Comment by JACKSONMEISTER** [comment]
Would you be so kind to provide a small code snippet on how to access the frame from the flutter side? (We're on Android)

**Comment by cloudwebrtc** [comment]
Use EventChannel.EventSink where you intercepted the videoFrame.
The code should look like this:
## Android (SurfaceTextureRenderer.java)
```java
public class SurfaceTextureRenderer extends EglRenderer {
  EventChannel.EventSink eventSink; //Reference eventSink from FlutterRTCVideoRenderer.
  ...
 // VideoSink interface.
  @Override
  public void onFrame(VideoFrame frame) {
    updateFrameDimensionsAndReportEvents(frame);
    super.onFrame(frame);

   ConstraintsMap params = new ConstraintsMap();
   params.putString("event", "onVideoFrame");

  /*copy  frame buffer to byte array*/
   byte[] bytes;
   Buffer buffer  = frame. getBuffer();
   bytes = new byte[buffer.data.remaining()];
   buffer.data.get(bytes);

   params.putByte("data", bytes); 

   /*send event to texture event channel*/
   eventSink.success(params.toMap());
  }
```
## Flutter (rtc_video_view.dart)
```dart
...
void eventListener(dynamic event) {
    final Map<dynamic, dynamic> map = event;
    switch (map['event']) {
      case 'onVideoFrame':
        dynamic videoFrame = map['data'];  // <== Got video buffer here.
        break;
...
  }
...
```

**Comment by JACKSONMEISTER** [comment]
I've been playing around with this for a few hours now, still not working...
Is there any chance that you will incorporate this feature into the package? 
Since you're acquiring the camera source no other package can access the camera so I think it's mandatory to provide a mechanism to access the current frame....

**Comment by cloudwebrtc** [comment]
@JACKSONMEISTER 
It is possible to add a Filtter interface to RTCVideoTrack, but since flutter is an asynchronous working mode, Videoframe callback to UI layer processing is not so easy. If it is one-way detection, you don't need to write the processed data back to WebRTC send stream, you can try use
[media_stream_track.dart](https://github.com/cloudwebrtc/flutter-webrtc/blob/master/lib/media_stream_track.dart#L57) Modify the interface to get RGB array data, and then use RGB directly for face detection.

**Comment by SemonCat** [comment]
hi, @cloudwebrtc ,

can you tell more detail about get rgb array from `media_stream_track.dart` ?

Thanks.

**Comment by FounderFoundry** [comment]
Hi @tbienias, have you figured out a solution for capture the video frame as suggested?

**Comment by FounderFoundry** [comment]
> @JACKSONMEISTER
> It is possible to add a Filtter interface to RTCVideoTrack, but since flutter is an asynchronous working mode, Videoframe callback to UI layer processing is not so easy. If it is one-way detection, you don't need to write the processed data back to WebRTC send stream, you can try use
> [media_stream_track.dart](https://github.com/cloudwebrtc/flutter-webrtc/blob/master/lib/media_stream_track.dart#L57) Modify the interface to get RGB array data, and then use RGB directly for face detection.

Hi @JACKSONMEISTER, can you be a bit more specific for your reply? Which function in the media_stream_track.dart file are you referring to? If you could provide the code line that holds the RGB array data will be of great help. Thanks

**Comment by catscs** [comment]
Good morning, see if anyone can help me.
I need to retrieve a byte buffer in the current frame for further image processing while in a WebRTC session. Thanks

**Comment by satyajitghana** [comment]
this issue was closed ? what was the updated solution ?

**Comment by FounderFoundry** [comment]
There is still no progress for a long time since. I have given up trying, unless the contributors of this module do something about this.

**Comment by satyajitghana** [comment]
Is it a `YUV_420` Image and we have to convert it to `RGB_888` ? Anyone tried this ?

**Comment by dipak140** [comment]
The image you get is always in YUV_420 format, you either manually convert it to RGB_888 or use a method to do it, for example in case of JAVA i used ScriptIntrinsicYuvToRGB to do the changes. @satyajitghana

**Comment by binvb** [comment]
> Use EventChannel.EventSink where you intercepted the videoFrame. The code should look like this:
> 
> ## Android (SurfaceTextureRenderer.java)
> ```java
> public class SurfaceTextureRenderer extends EglRenderer {
>   EventChannel.EventSink eventSink; //Reference eventSink from FlutterRTCVideoRenderer.
>   ...
>  // VideoSink interface.
>   @Override
>   public void onFrame(VideoFrame frame) {
>     updateFrameDimensionsAndReportEvents(frame);
>     super.onFrame(frame);
> 
>    ConstraintsMap params = new ConstraintsMap();
>    params.putString("event", "onVideoFrame");
> 
>   /*copy  frame buffer to byte array*/
>    byte[] bytes;
>    Buffer buffer  = frame. getBuffer();
>    bytes = new byte[buffer.data.remaining()];
>    buffer.data.get(bytes);
> 
>    params.putByte("data", bytes); 
> 
>    /*send event to texture event channel*/
>    eventSink.success(params.toMap());
>   }
> ```
> 
> ## Flutter (rtc_video_view.dart)
> ```dart
> ...
> void eventListener(dynamic event) {
>     final Map<dynamic, dynamic> map = event;
>     switch (map['event']) {
>       case 'onVideoFrame':
>         dynamic videoFrame = map['data'];  // <== Got video buffer here.
>         break;
> ...
>   }
> ...
> ```

我可以把这个feature实现提交一个pr吗？

**Comment by cloudwebrtc** [comment]
@binvb  我认为可以, 
可以在这个类中加入一些控制比如，一个开关exportFrame, 和一个onFrame 回调.
https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/native/rtc_video_renderer_impl.dart

```dart
enum RTCVideoFrameFormat {
  kI420,
  kRGBA,
}

class RTCVideoFrame {
   RTCVideoFrameFormat fromat;
   Uint8List data;
   RTCVideoFrame(this.fromat, this.data);
}

class RTCVideoRenderer {
.....
Function(Uint8List rawData)? onFrame;

///  frameCount 获取帧的数量，例如 1帧 的时候可以用于截图
///  -1 则表示一直输出.
///  format 默认输出I420 这里可以先仅实现I420,但是建议保留格式参数向native 层传递
/// 以便后续可以支持更多个格式输出
Future<void> exportFrame(bool enabled, {int? frameCount = -1,  RTCVideoFrameFormat format = kI420}) async {
   ....
}

...
void eventListener(dynamic event) {
    final Map<dynamic, dynamic> map = event;
    switch (map['event']) {
      case 'onVideoFrame':
        dynamic data = map['data']; 
        dynamic format = map['format']; 
        onFrame?.call(RTCVideoFrame(format, data));
        break;
...
  }
...

}```

**Comment by cloudwebrtc** [comment]
hey @catscs, what are the image formats supported by mlkit? YUV420/RGBA/MJPEG, or something else.

**Comment by binvb** [comment]
> Hello, do you know how to convert VideoFrame to image o InputImage in mlkit by flutter?

here you can try: https://github.com/flutter-webrtc/flutter-webrtc/blob/a9cc108ac69691c2ec998043c8a495d3fcf3905a/android/src/main/java/com/cloudwebrtc/webrtc/record/FrameCapturer.java#LL39C16-L39C16

**Comment by catscs** [comment]
I don't know very well which one uses this plugin. 
https://pub.dev/packages/google_mlkit_face_detection
Thanks!!

**Comment by cloudwebrtc** [comment]
https://developers.google.com/android/reference/com/google/mlkit/vision/common/InputImage.ImageFormat

it supports YUV420 (I420), NV21, YV12

**Comment by catscs** [comment]
do you know how I can convert it to that format as I am very new to it.

**Comment by cloudwebrtc** [comment]
It looks like there is no need to convert the default format of webrtc when I420

**Comment by pavan901** [comment]
hey maybe they didnt add this feature to webrtc or I don't find it please help me for that I want to obtain video stream in the ios and android side . i can get that in dart side but don't find anything for the ios and android side
