### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by mliitfall** [cloudwebrtc/flutter-webrtc#12]
Hi again,
I'm trying to use RTCPeerConnection,

`var peerConnection = RTCPeerConnection("{'iceServers': []}");`

problem is, just add this line show an error message on flutter :

`Another exception was thrown: MissingPluginException(No implementation found for method listen on channel cloudwebrtc.com/WebRTC/peerConnectoinEvent{'iceServers': []})`

Anything wrong?

**Comment by cloudwebrtc** [comment]
Hi,  you need use createPeerConnection  method  for rtc_peerconnection_factory.dart,  because Peerconnection needs to be created from the native layer, it needs asynchronous mode.
like this:
```dart
Map<String, dynamic> configuration = {
      "iceServers": [ {"url": "stun:stun.l.google.com:19302"}, ]
    };
    final Map<String, dynamic> constraints = {
      "mandatory": {},
      "optional": [ {"DtlsSrtpKeyAgreement": false}, ],
    };

var peerConnection =
      await createPeerConnection(configuration, constraints);
```

**Comment by mliitfall** [comment]
Is there any documentation using webrtc on flutter/native?
Because it's different from webrtc on web. I'm trying to check if my peerconncetion is onIceCandidate

```
stream() async{
    Map<String,dynamic> configuration = {
      "iceServers" : []
    };

    final Map<String, dynamic> constraints = {
      "mandatory": {},
      "optional": [ {"DtlsSrtpKeyAgreement": false}, ],
    };

    peerConnection = await createPeerConnection(configuration, constraints);
    print('ok');
    peerConnection.onIceCandidate = gotIceCandidate;
    peerConnection.onIceConnectionState = onIceState;
  }

  void gotIceCandidate(RTCIceCandidate iceCandidate){
    if (iceCandidate.candidate != null){
      print("onIceCandidate");
    }
 }

  void onIceState(RTCIceConnectionState iceConnectionState){
    if (iceConnectionState.index == 3){//CONNECTED
      print("connected");
    }else if(iceConnectionState.index == 5){//FAILED
      print("failed");
    }
  }
```
After connecting, I can do peerConnection.onTrack on web, but there is no onTrack on this library?

**Comment by cloudwebrtc** [comment]
There are some differences between the API dart and the web. You can refer to https://github.com/cloudwebrtc/flutter-webrtc-demo first, and the API documentation will be added later.
 
The dart version of onTrack API looks like this:
```dart
typedef void AddTrackCallback(MediaStream stream, MediaStreamTrack track);
typedef void RemoveTrackCallback(MediaStream stream, MediaStreamTrack track);
....
class RTCPeerConnection {
...
  AddTrackCallback onAddTrack;
  RemoveTrackCallback onRemoveTrack;
```
Use in code:
```dart
pc.onAddTrack = (track) {
     //
};

pc.onRemoveTrack = (track) {
     //
};
```
You can refer to the code in flutter-webrtc-demo. The example can be P2P video call.
[flutter-webrtc-demo://lib/src/call_sample/signaling.dart](https://github.com/cloudwebrtc/flutter-webrtc-demo/blob/master/lib/src/call_sample/signaling.dart)

**Comment by mliitfall** [comment]
Hi, Thanks for the answer. I have tried the demo.
But still stack on finding a way to get the EventHandler on PeerConnection.
In web, you can use [onTrack](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/ontrack) to handle event like this, when server give a video/audio, the event will awake and activate it.

```Javascript
private remoteAudio: HTMLAudioElement;
private remoteVideo: HTMLVideoElement;

this.peerConnection.ontrack = (event) => { this.gotRemoteTrack(event) };

gotRemoteTrack(event) {
        switch (event.track.kind) {
            case "video":
                this.remoteVideo.srcObject = event.streams[0];
                break;
            case "audio":
                this.remoteAudio.srcObject = event.streams[0];
                break;
        }
    }
```

Is [RTCVideoRenderer](https://pub.dartlang.org/documentation/flutter_webrtc/latest/rtc_video_view/RTCVideoRenderer-class.html) srcObject is MediaStream? I actually do not need a MediaStream because I'm not creating a p2p video call, I just want to stream live through server.

**Comment by cloudwebrtc** [comment]
Hi, in the flutter version, RTCVideoRenderer is only used to display video stream, AudioTrack is played in the native layer, you can only get a track object in the dart layer to mute / unmute audio stream.

**Comment by mliitfall** [comment]
So, in order to video stream, I need to getUserMedia?

```Dart
Future<MediaStream> createStream() async {
    final Map<String, dynamic> mediaConstraints = {
      'audio': true,
      'video': {
        'mandatory': {
          'minWidth':
              '640', // Provide your own width, height and frame rate here
          'minHeight': '480',
          'minFrameRate': '30',
        },
        'facingMode': 'user',
        'optional': [],
      }
    };

    MediaStream stream = await navigator.getUserMedia(mediaConstraints);
    if(this.onLocalStream != null){
      this.onLocalStream(stream);
    }
    return stream;
  }
```
What is facingMode and optional?

**Comment by mliitfall** [comment]
Could you give a demo/example to streaming video from server with this plugin?

**Comment by cloudwebrtc** [comment]
The next time we update demo, we add an example of how flutter-webrtc interacts with SFU servers. But now, you can handle it on pc.onAddTrack.

**Comment by mliitfall** [comment]
```
I/libjingle(32252): (channel.cc:2033): Setting remote video description
I/libjingle(32252): (webrtcvideoengine.cc:721): SetSendParameters: {codecs: [VideoCodec[97:H264]], extensions: [], max_bandwidth_bps: -1, }
I/libjingle(32252): (webrtcvideoengine.cc:556): Internally supported codecs: {VideoCodec[0:VP8], VideoCodec[0:VP9], VideoCodec[0:red], VideoCodec[0:ulpfec]}
I/libjingle(32252): (webrtcvideoengine.cc:568): Codecs supported by the external encoder factory: {}
E/libjingle(32252): (webrtcvideoengine.cc:665): No video codecs supported.
E/libjingle(32252): (webrtcsession.cc:350): Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..
```

I got no video codecs supported. What video codec is RTCVideoRenderer support? Is same as [this](https://developer.android.com/guide/topics/media/media-formats)?

**Comment by cloudwebrtc** [comment]
WebRTC supports VP8/VP9 by default, and if some devices support H264 HW codec, you can check if your device supports H264 HW.

**Comment by mliitfall** [comment]
Is it testable in Emulator? or need a real device?

**Comment by cloudwebrtc** [comment]
You need a real device.
