### ISSUE TITLE
FrameRate control

### ISSUE THREAD

**Issue by GuillaumeJulien** [cloudwebrtc/flutter-webrtc#123]
**Is your feature request related to a problem? Please describe.**
We can't fix the frame rate like FrameRate : 20 or apply constraint after on mediaTrackVideo  
**Describe the solution you'd like**
Add on GetUser getUserMedia in mandatory constrains "maxFrameRate" or applyConstraint Feature.

**Comment by cloudwebrtc** [comment]
Maybe a bug. I need to do more testing.

**Comment by rostopira** [comment]
It doesn't actually implemented in WebRTC framework itself
According to [source](https://webrtc.googlesource.com/src/+/master/sdk/android/src/java/org/webrtc/Camera1Session.java#137) it just finds closest to specified framerate that supported by camera

It's still possible to make camera capturer drop frames, by inheriting capturer classes, but it's requires few hours of boring boirelplate
But why on earth would someone limit framerate? It's crucial for user experience

**Comment by GuillaumeJulien** [comment]
> It doesn't actually implemented in WebRTC framework itself 
For the only for the ApplyConstraint no ? 
> But why on earth would someone limit framerate? 
Haha,  I use to communicate with  Chromium on a TinkerBoard and it can't show more than 24fps with  2 persons  and 15fps with 3 

I can make you a PR but i haven't any idea to how to make that on ios atm

**Comment by rostopira** [comment]
If you know how to do it, then you can make it in fork
I really doubt that any other user of this plugin would need such feature

**Comment by d3fkon** [comment]
@rostopira 
I would like to limit the FPS to reduce the CPU load VP8 brings to the table. It would be great if I can reduce the resolution of the camera too
