### ISSUE TITLE
run error in ios 12.4.1 when use_frameworks!

### ISSUE THREAD

**Issue by byerman** [cloudwebrtc/flutter-webrtc#124]
i use flutter-socket-io and flutter_webrtc plugin 
the flutter-socket-io plugin require Podfile must be add use_frameworks!
so when i run app in ios 12.4.1 device
i get the error 

Class RTCCVPixelBuffer is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1c3326018) and /private/var/containers/Bundle/Application/4AA1C93A-A47B-4E47-B1F7-905608836D54/Runner.app/Frameworks/WebRTC.framework/WebRTC (0x103915990). One of the two will be used. Which one is undefined.

i don't know the error how to trigger
is relate use_frameworks! ？
or the other reason? GOOGLE_WEBRTC version ?
please help

**Comment by cloudwebrtc** [comment]
It seems to be a known issue, related to the system's WebKit.
