### ISSUE TITLE
获取设备列表调用navigator.getSources();安卓平台报错

### ISSUE THREAD

**Issue by felixcloud** [cloudwebrtc/flutter-webrtc#125]
Hello,

我在flutter-webrtc-demo中调用navigator.getSources();

IOS平台能正常运行，但在Android平台报以下错误：
`Unable to getSources: Unsupported value: com.cloudwebrtc.webrtc.utils.ConstraintsArray@e2f207a`

**Comment by cloudwebrtc** [comment]
@felixcloud 有更详细的日志吗？

**Comment by felixcloud** [comment]
> @felixcloud 有更详细的日志吗？

`E/MethodChannel#FlutterWebRTC.Method( 2518): Failed to handle method call
E/MethodChannel#FlutterWebRTC.Method( 2518): java.lang.IllegalArgumentException: Unsupported value: com.cloudwebrtc.webrtc.utils.ConstraintsArray@47348fc
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:57)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult.lambda$success$0$AnyThreadResult(AnyThreadResult.java:18)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult$$Lambda$0.run(Unknown Source:4)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult.post(AnyThreadResult.java:33)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult.success(AnyThreadResult.java:18)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.getSources(FlutterWebRTCPlugin.java:830)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.onMethodCall(FlutterWebRTCPlugin.java:142)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#FlutterWebRTC.Method( 2518): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by cloudwebrtc** [comment]
参数格式有误？
