### ISSUE TITLE
I can't integrate mediasoup-v3 with this library

### ISSUE THREAD

**Issue by VNAPNIC** [cloudwebrtc/flutter-webrtc#132]
I can't integrate mediasoup-v3 with this library
https://mediasoup.org/documentation/v3/communication-between-client-and-server

**Comment by cloudwebrtc** [comment]
Adapting mediasoup requires a high-level signaling layer.
https://github.com/cloudwebrtc/flutter-mediasoup-client
When flutter-webrtc completes the unified-plan function, the library can be developed.
