### ISSUE TITLE
cocoapods could not find compatible versions for pod flutter_webrtc 

### ISSUE THREAD

**Issue by VNAPNIC** [cloudwebrtc/flutter-webrtc#134]
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "flutter_webrtc":
  In Podfile:
    flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`)

Specs satisfying the `flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`)` dependency were found, but they required a higher minimum deployment target.

[!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by cloudwebrtc** [comment]
@VNAPNIC If you are relying on flutter-webrtc in your own project, you need to modify the Podfile to uncomment the `# platform :ios, '9.0'`.
flutter-webrtc uses GooglWebRTC's native SDK, which dependent on iOS 9.0 or higher
