### ISSUE TITLE
Is it possible to connect SkyWay server with api key?

### ISSUE THREAD

**Issue by yukitaka13-1110** [cloudwebrtc/flutter-webrtc#135]
Just usage question.
I want to connect SkyWay server with api key.
But, I don't have any idea.
I tried to find rest request in source code, but couldn't find.

What should I do ?

**Comment by cloudwebrtc** [comment]
@yukitaka13-1110 flutter-webrtc is just a plugin, it does not have built-in signaling function, you need to use dart-lang to develop docking SkyWay SDK, and exchange SDP at the appropriate time to call flutter-webrtc to complete media communication.
