### ISSUE TITLE
onWebRtcAudioRecordSamplesReady method is not triggered

### ISSUE THREAD

**Issue by nickdiam** [cloudwebrtc/flutter-webrtc#148]
**Describe the bug**
I'm consuming the VideoFileRenderer class which is supposed to record video and audio of a WebRTC video call. 

Audio recording has an issue because onWebRtcAudioRecordSamplesReady(line 265, VideoFileRenderer class) method is not triggered at all. I'm not sure how onWebRtcAudioRecordSamplesReady is triggered. If I'm not using VideoFileRenderer properly please correct me.

**To Reproduce**

    AudioSamplesInterceptor audioInterceptor = new AudioSamplesInterceptor();
    VideoFileRenderer recording =  new VideoFileRenderer("mypath", rootEglBase.eglBaseContext, true);                     
    localVideoTrack.addSink(recording);                    
    audioInterceptor.attachCallback(100, recording); `

**Expected behavior**
A video file should be created with the video and audio of the WebRTC call session. Audio recording seems to have an issue.

* **OS**: Android
* **OS version**: 8

**Comment by cloudwebrtc** [comment]
This question looks like only @rostopira  can help, but he has been busy recently.

**Comment by rostopira** [comment]
Make sure you have passed correct audio track as parameter
Check out this file: https://github.com/cloudwebrtc/flutter-webrtc/blob/master/android/src/main/java/org/webrtc/audio/WebRtcAudioTrackUtils.java
Try to find corresponding emojis (they just work better than regular tags), you may find issue quickly
Also, please specify, which audiotrack you are trying to record (local or remote)

P.S.: right at this moment I'm setting up webrtc framework build environment on my machine.
I'm fed up with bugs that won't be ever fixed, hardcoded constants that couldn't be changed and ugly hacks to make such basic thing as recording possibly.
So, you can expect this to be rewritten from scratch.
