### ISSUE TITLE
Raise the bandwidth for DataChannel

### ISSUE THREAD

**Issue by TheSquad** [cloudwebrtc/flutter-webrtc#151]
**Is your feature request related to a problem? Please describe.**
Right now, trying to send large files, it will be chunked into 262528 max bytes.

**Describe the solution you'd like**
Allow the possibility to raise the chunk size

**Describe alternatives you've considered**
I have tried to modify the SDP by adding `b=AS:1638400`, didn't change the chunk size.

**Comment by cloudwebrtc** [comment]
`AS` can only limit bandwidth, I think you can do some blocks before sending and send them one by one according to the specified size.

**Comment by TheSquad** [comment]
you are right, but I though by default the bandwidth was already limited, I wanted to raise that limit.
If I try to send smaller blocks, it will get chunked also at 262528 bytes
