### ISSUE TITLE
No implementation found for method createVideoRenderer on channel FlutterWebRTC.Method

### ISSUE THREAD

**Issue by darwin-morocho** [cloudwebrtc/flutter-webrtc#157]
after upgrate to flutter_webrtc: 0.2.1 on iOS the app Crash with the next error

```
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method createVideoRenderer on channel FlutterWebRTC.Method))
```

**Comment by cloudwebrtc** [comment]
Please make sure to use Flutter version above v1.12.x.

**Comment by DQvsRA** [comment]
Having the same problem running on iOS
```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method createVideoRenderer on channel FlutterWebRTC.Method)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      RTCVideoRenderer.initialize (package:flutter_webrtc/rtc_video_view.dart:25:24)
#3      _VideoLiveState.initRenderers (package:flutter_video_live/main_webrtc.dart:95:31)
#4      _VideoLiveState.initState (package:flutter_video_live/main_webrtc.dart:362:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4695:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4531:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3501:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3257:20)
#9      ComponentElement.performRe<…>
```

`(package:flutter_video_live/main_webrtc.dart:95:31)`:
```
await _rtcPreviewRenderer.initialize();
```

Flutter version:
```
Flutter 1.21.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision f25bd9c55c (3 weeks ago) • 2020-07-14 20:26:01 -0400
Engine • revision 99c2b3a245
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
```

**Comment by ching7** [comment]
Problem: IOS integrates the flitter application as the video stream load, and uses the flitter and the flitter plug-in flitter webrtc
The way of integrating flutter into IOS application is to use- https://flutter.cn/docs/development/add-to-app/ios/project-setup  Option B, option B - embedded frameworks in Xcode
When the flitter application is running, when it involves calling the native camera, it will call the native IOS webrtc through flitter webrtc through native, and an error will be reported
My version is:
[✓] Flutter (Channel dev, 1.24.0-10.1.pre, on macOS 11.1 20C69 darwin-x64, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
✗ Unable to locate Android SDK.
Install Android Studio from:  https://developer.android.com/studio/index.html
On first launch it will assist you in installing the Android SDK components.
(or visit  https://flutter.dev/docs/get-started/install/macos#android -setup for detailed
instructions).
If the Android SDK has been installed to a custom location, please use
`flutter config --android-sdk` to update to that location.
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
Chrome.app/Contents/MacOS/Google  Chrome)
! Cannot find Chrome. Try setting CHROME_ EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (3 available)

**Comment by kurtiev** [comment]
Why it's closed? Still relevant for now.

**Comment by Snooker-shoot** [comment]
are you fixed it？ @kurtiev

**Comment by kurtiev** [comment]
Unfortunately no. Client postponed the project. @Snooker-shoot
