### ISSUE TITLE
the demo:flutter-webrtc-demo-master is also crash, on flutter 1.12.13 。Debug is ok ,but release will crash .

### ISSUE THREAD

**Issue by cuijinfeng68** [cloudwebrtc/flutter-webrtc#162]
**Describe the bug**
 flutter-webrtc-demo-master crash in release, debug is ok .
**To Reproduce**

**Expected behavior**
flutter-webrtc-demo-master is also crash Debug is ok ,but release will crash .
**Platform information**

* **Flutter version**: 
flutter 1.12.13
* **Plugin version**:
 0.2.2
* **OS**: 
Android
* **OS version**:

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/cloudwebrtc/flutter-webrtc/commit/4966ab01bf256ce27f9d32b96a4768100e9e664e
