### ISSUE TITLE
Invalid `flutter_webrtc.podspec` file: syntax error

### ISSUE THREAD

**Issue by vuitv** [cloudwebrtc/flutter-webrtc#163]
[!] Failed to load 'flutter_webrtc' podspec: 
    [!] Invalid `flutter_webrtc.podspec` file: syntax error, unexpected '\n', expecting =>.

     #  from /Users/vuitv/Documents/Wido/ss-datesmatch-app/ios/.symlinks/plugins/flutter_webrtc/ios/flutter_webrtc.podspec:13
     #  -------------------------------------------
     #    s.license          = { :file => '../LICENSE' }
     >    s.author           = {{ 'CloudWebRTC' => 'duanweiwei1982@gmail.com' }
     #    s.source           = { :path => '.' }
     #  -------------------------------------------

**Comment by cherrydat** [comment]
replace {{ 'CloudWebRTC' => 'duanweiwei1982@gmail.com' } with { 'CloudWebRTC' => 'duanweiwei1982@gmail.com' }

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/cloudwebrtc/flutter-webrtc/commit/f95c99134886d0f55ff8c00df6c5254294811218
