### ISSUE TITLE
Got SocketException

### ISSUE THREAD

**Issue by theantiqa** [cloudwebrtc/flutter-webrtc#165]
I/flutter (19694): connect to wss://demo.cloudwebrtc.com:4443
I/flutter (19694): Closed by server [500 => SocketException: OS Error: Connection refused, errno = 111, address = demo.cloudwebrtc.com, port = 47784]!

**Comment by cloudwebrtc** [comment]
@theantiqa 
The demo server is down and has restarted, please try again.

**Comment by theantiqa** [comment]
can i use this server in my app or i have to buy another one.
If not then tell me where can I setup webrtc setup in free and what can i do for setup server and what changes need to do in app. step by step guidance.

**Comment by cloudwebrtc** [comment]
Please refer to https://github.com/cloudwebrtc/flutter-webrtc-server.

**Comment by theantiqa** [comment]
can i use this demo server in my app?

**Comment by cloudwebrtc** [comment]
I think you can use it for testing.

**Comment by theantiqa** [comment]
Can you help me to setup server in aws? can you give me your skype?
