### ISSUE TITLE
iOS: Incompatibility with FirebaseFirestore because of libyuv headers

### ISSUE THREAD

**Issue by MrAlek** [cloudwebrtc/flutter-webrtc#168]
See discussion in: https://github.com/firebase/firebase-ios-sdk/issues/4537

Because of flattened headers inside `libyuv.h` coming from https://github.com/waitingsnow/libyuv-iOS/blob/master/headers/libyuv.h the iOS pod of `flutter-webrtc` has become incompatible with `FirebaseFirestore` on iOS.

The `waitingsnow` mirror of libyuv is two years behind upstream and isn't actively maintained but one could create a new fork to fix the issue https://chromium.googlesource.com/libyuv/libyuv/+/refs/heads/master/include/libyuv.h

The question is who will maintain that mirror. If @cloudwebrtc could, that would be amazing.

**Comment by duongtruong12** [comment]
excuse me how can i use that, i had upgrade all plugin to newest version flutter_webrtc and cloud_firestore but it can still get error 'cstddef' file not found while building ios

**Comment by MrAlek** [comment]
@duongtruong12 I don't think the maintainers have cut out a release yet. What you can do is to point `flutter_webrtc` against the `master` branch like this in your pubspec:
```
  flutter_webrtc:
    git:
      url: https://github.com/cloudwebrtc/flutter-webrtc
      ref: master
```
