### ISSUE TITLE
RTCMediaStream methods addTrack and removeTrack not implemented

### ISSUE THREAD

**Issue by rostopira** [cloudwebrtc/flutter-webrtc#17]
RTCMediaStream methods addTrack and removeTrack not implemented

**Comment by rostopira** [comment]
Long story short: how to hotswap rear/front camera after connection was established? Such a basic feature

**Comment by rostopira** [comment]
I've already spent half of a day to implement this methods, but another phone just don't receive new stream

**Comment by cloudwebrtc** [comment]
If you use addTrack and removeTrack to switch cameras, you need re-offer/answer to notify the peer of track changes.
I suggest add a SwitchCamera method for RTCMediaStream to switch directly to the VideoCapture interface.

**Comment by rostopira** [comment]
@cloudwebrtc thanks for response, I've already implemented switch camera method yesterday, and provided pull request
I've accidentally included implementation of one TODO and fix for android data channel in this PR too, could you please review it and merge, if possible?
