### ISSUE TITLE
Error: Not found: 'dart:html'

### ISSUE THREAD

**Issue by Condelab** [cloudwebrtc/flutter-webrtc#179]
**Describe the bug**
am getting Error: Not found: 'dart:html' when i try to use 
**To Reproduce**

**Expected behavior**
Compiler message:
[        ] flutter_webrtc_0_2_2/lib/web/rtc_video_view.dart:3:8: Error: Not found: 'dart:html'
[        ] import 'dart:html' as HTML;
[        ]        ^
....
**Platform information**
Mac OS X 10.15.2 19C57
* **Flutter version**: 
1.14.7-pre.40
* **Plugin version**:
0.2.2
* **OS**: 
Android
* **OS version**:
9.0

**Comment by tomamatics** [comment]
make sure your library imports are fine.

// correct
import 'package:flutter_webrtc/webrtc.dart';

// incorrect, causes exception above
import 'package:flutter_webrtc/rtc_video_view.dart';

hope this helps.
