### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by rlee1990** [cloudwebrtc/flutter-webrtc#18]
Can this be used with firebase?

**Comment by rostopira** [comment]
@rlee1990 yes, I use firebase as signaling server with this plugin

**Comment by rlee1990** [comment]
Any docs on setting this up just really lost on how to set this up with firebase.
@rostopira

**Comment by rostopira** [comment]
@rlee1990 you can use my basic sample, but keep in mind, that this example is incomplete, it doesn't include TURN config and ICE-connection/ICE-gathering state listeners

class FirebaseRtcClient {
  FirebaseRtcClient(this.target, this.roomId) {
    isInitiator = roomId == null;
    if (roomId != null) {
      _dbRef = FirebaseDatabase.instance.reference().child("t/$roomId");
    } else {
      _dbRef = FirebaseDatabase.instance.reference().child("t").push();
      roomId = _dbRef.key;
    }
  }

  //Public vars
  bool isInitiator;
  User target;
  String roomId;
  var useTurn = false;
  StreamStateCallback onAddStream;
  StreamStateCallback onRemoveStream;

  //Public getters
  get state => _state;

  //Abstract vars
  final Map<String, dynamic> _constraints = {
    'mandatory': {
      'OfferToReceiveAudio': true,
      'OfferToReceiveVideo': true,
    },
    'optional': [{'DtlsSrtpKeyAgreement': true}]
  };

  //Private vars
  var isFrontFacing = false;
  RTCDataChannel _myDataChannel;
  DatabaseReference _dbRef;
  MediaStream _localStream;
  RTCPeerConnection _peerCon;
  var _state = SignalingState.CallStateNew;
  StreamSubscription<Event> _listener;
  Map<String, dynamic> _iceServers = {
    'iceServers': [
      {'url': 'stun:stun.l.google.com:19302'},
    ]
  };

  connect() async {
    await _createStream();
    if (useTurn)
      await _loadTurn();
    _peerCon = await createPeerConnection(_iceServers, _constraints);
    if (_localStream != null)
      _peerCon.addStream(_localStream);
    _peerCon.onIceCandidate = (candidate) {
      this._send({
        't': 'ice',
        'smi': candidate.sdpMlineIndex,
        'sm': candidate.sdpMid,
        'c': candidate.candidate,
        'id': S.userId
      });
    };
    _peerCon.onAddStream = onAddStream;
    _peerCon.onRemoveStream = onRemoveStream;
    if (isInitiator) {
      var dci = RTCDataChannelInit();
      dci.id = 1;
      _myDataChannel = await _peerCon.createDataChannel("commands", dci);
    } else {
      _peerCon.onDataChannel = (dataChannel) {
        print("On new data channel");
        dataChannel.onMessage = _onDataChannelMessage;
      };
    }
    if (isInitiator) {
      await _createOffer();
    }
    _listener = _dbRef.onChildAdded.listen((event) {
      final val = event.snapshot.value;
      if (event.snapshot.key == '0' //Zero reserved for future use
          || val["id"] == S.userId)
        return;
      if (val["t"] == "ice") {
        _peerCon.addCandidate(
            RTCIceCandidate(val['c'], val['sm'], val['smi']));
        return;
      }
      if (val['t'] == "ans") {
        assert(isInitiator);
        _peerCon.setRemoteDescription(
            RTCSessionDescription(val['sdp'], val['tp']));
        return;
      }
      if (val['t'] == "off") {
        assert(!isInitiator);
        _peerCon.setRemoteDescription(
            RTCSessionDescription(val['sdp'], val['tp']));
        _createAnswer();
        return;
      }
    });
    if (isInitiator)
      _sendPush();
  }

  void _onDataChannelMessage(String msg) async {
    //TODO
  }

  void close() {
    _listener?.cancel();
    _dbRef.remove();
    _localStream?.dispose();
    _localStream = null;
    _peerCon?.close();
  }

  _loadTurn() async {
    //TODO
  }

  Future<void> _send(data) async =>
    await _dbRef.push().set(data);

  _createStream() async {
    final Map<String, dynamic> mediaConstraints = {
      'audio': true,
      'video': {
        'mandatory': {
          'minWidth': '1280',
          'minHeight': '720',
          'minFrameRate': '30'
        },
        'facingMode': 'environment'
      },
      'facingMode': 'environment',
      'optional': []
    };
    _localStream = await navigator.getUserMedia(mediaConstraints);
  }

  _createOffer() async {
    final off = await _peerCon.createOffer(_constraints);
    await _peerCon.setLocalDescription(off);
    await _send({
      't': 'off',
      'sdp': off.sdp,
      'tp': off.type,
      'id': S.userId
    });
  }

  void _createAnswer() async {
    final ans = await _peerCon.createAnswer(_constraints);
    await _peerCon.setLocalDescription(ans);
    await _send({
      't': 'ans',
      'sdp': ans.sdp,
      'tp': ans.type,
      'id': S.userId
    });
  }

  void _sendPush() {
    const url = "https://onesignal.com/api/v1/notifications";
    http.post(url, headers: {
      "Content-Type": "application/json"
    }, body: json.encode({
      "app_id": appId,
      "data": {
        "id": S.userId,
        "v": roomId,
        "t": 1
      },
      "content_available": true,
      "ttl": 120,
      "priority": 10,
      "include_player_ids": [target.pushId]
    })).then((response) {
      print("OneSignal result: ${response.body}");
    }, onError: (err) {
      print("OneSignal error: $err");
    });
  }

}

**Comment by rlee1990** [comment]
thanks

**Comment by rostopira** [comment]
@rlee1990 please, close issue now, firebase isn't related to this plugin, and it's not a stackoverflow

**Comment by harshapulikollu** [comment]
@rostopira  can you please proper example (sample app) on how to use firestore and webrtc (this) plug to make p2p video calls. I'm unable to form things in a way. please explain how to get Ice connection and stun/turn server and how to use firestore for that. I'm lost in all those things. if feasible **provide working sample app with firebase as signalling server.** Thanks in advance.

**Comment by rostopira** [comment]
@harshapulikollu yeah, sure, just give me a single reason to do that for you
That's not 10 minutes task
If you don't understand code I've shared above, then just go RTFM, I've spent more than year to learn and understand how WebRTC works without anyones help, so why do you think somebody is going to do that for you?
**Actually**, I'm going to make working sample app no both Firebase RTDB and Firestore using code I have already, but I have some real job t be done
So only god knows when I'll get some free time
And only god knows, if you will understand how my demo works, if you don't understand a difference between STUN and TURN (just google it, really)

**Comment by harshapulikollu** [comment]
@rostopira sir, I said **If feasible**(hope you know meaning of it) then provide doesn't mean you have to use words like RTFM on a stranger, better mind your words when you are on a public platform. If I can found it everything on google then I don't have to ask you at all sir. I just asked if you can provide please do except that I'm not begging you and now I feel very bad myself why I asked such a person. It's a community where if you can help and teach others, then do it. I you can't then just you can't.
