### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by fzyzcjy** [cloudwebrtc/flutter-webrtc#180]
**Is your feature request related to a problem? Please describe.**
Thanks for the library! I wonder whether this is production ready for, say, an app with millions of users?
For instance, does it have *echo surpression*, and how much data does it need (e.g. ~20KB/s?)
Thanks!

**Comment by cloudwebrtc** [comment]
flutter-webrtc only dart API package GooglWebRTC binary SDK, so its technical parameters are consistent with Google's WebRTC.

**Comment by fzyzcjy** [comment]
Oh great! Thanks :)
