### ISSUE TITLE
Default Android logs are way too verbose

### ISSUE THREAD

**Issue by doppio** [cloudwebrtc/flutter-webrtc#187]
When using this plugin on Android (haven't tested iOS), it floods my Debug Console in VS Code with low-priority logs. I get this more than once per second:

> I/org.webrtc.Logging( 3029): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

The plugin shouldn't default to logging this much, or at least provide a way to disable all this logging.

**Comment by doppio** [comment]
Closing this because I see that this is coming from the WebRTC Java implementation, not the plugin. If anyone knows of a way to shut this up/filter it in VS Code, I'd love to know. 😛

**Comment by liquidiert** [comment]
For Android Studio one can use this neat little trick :+1: : 
https://stackoverflow.com/questions/41709658/filter-messages-in-android-studio-debug-console

**Comment by joknu1** [comment]
You can
```
        val logging = org.webrtc.Logging()
        java.util.logging.Logger.getLogger("org.webrtc.Logging").level = Level.OFF
```
to shut it up.

**Comment by diogobratti** [comment]
Where should I put that?

**Comment by tgrushka** [comment]
The fact this plugin still does not allow configuration of logging level by environment or method call is enormously aggravating.

The instructions from @joknu1 are on the right track, but it took hours to figure out. A complete answer would not have taken much effort, but would have saved me hours of frustration, so here it is:

1. Add the following to the **end** of `android/app/build.gradle`

  - (**use the same version as in https://github.com/flutter-webrtc/flutter-webrtc/blob/main/android/build.gradle**):

```groovy
dependencies {
    implementation 'io.github.webrtc-sdk:android:114.5735.10'
}
```

3. Edit `android/app/src/main/kotlin/com/example/myapp/MainActivity.kt` (or whatever path it actually is -- just "quick open" `MainActivity.kt` in VS Code and you should find it):

```kt
package ... // don't change this line

import android.os.Bundle
import io.flutter.embedding.android.FlutterActivity
import java.util.logging.Level

// replace the `MainActivity` stub with the following:
class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        val logging = org.webrtc.Logging()
        // set Level to whatever level you want, per java.util.logging.Level
        java.util.logging.Logger.getLogger("org.webrtc.Logging").level = Level.OFF

        super.onCreate(savedInstanceState)
    }
}
```

4. Run the Flutter app. The `org.webrtc.Logging` messages should be gone, **but a whole bunch of other messages still get printed, apparently from the C++ side of the plugin.**

At least this deals with this part of the message. Feature request coming for setting the log level on this plugin...
