### ISSUE TITLE
关于回声抑制和噪声消除

### ISSUE THREAD

**Issue by HnLong** [cloudwebrtc/flutter-webrtc#195]
@cloudwebrtc 你好
      请问实现了回声消除和噪声抑制吗？测试到flutter-webbrtc-sample 回声很大。如有api 请告知是哪几个 ，谢！

**Comment by cloudwebrtc** [comment]
flutter-webrtc使用标准GooglWebRTC SDK封装，所以回声消除降噪等参数默认是打开状态。如果是测试两个设备离的太近，应该不是SDK本身的问题。
