### ISSUE TITLE
WebRTC sets Android device state to in-call on app launch

### ISSUE THREAD

**Issue by Sociosoftware** [cloudwebrtc/flutter-webrtc#198]
**Describe the bug**
The app sets the Android "In-Call" state when launched, even if no WebRTC features are used. It maintains this state until the app is closed. If the app is in the background, but not yet closed, it will still maintain the in-call state. This is only happening on Android and only on the master branch.

Effects:
When adjusting the volume, the device as seen as "In-Call" and the in call volume is instead adjusted. This has adverse effects on media consumption, even outside of the app. Even if the app is in the background, when a user tries to play media in another app and adjust the volume, the In-Call volume is instead adjusted. Essentially it limits the user's ability to adjust any volume besides the in-call volume while the app is open. It also makes users think that the app is recording them. 

Additional info:
This only happens on the master branch. It doesn't require any permissions to be granted and it doesn't require a webrtc session to have ever been started. I'm currently using the master branch for a fix that has not gone into 0.2.6 yet. I notice different output in the terminal when launching the app using webrtc master that is not present on the stable branch:
D/FlutterWebRTCPlugin(25092): Starting the audio manager...
D/FlutterWebRTCPlugin(25092): onAudioManagerDevicesChanged: [SPEAKER_PHONE, EARPIECE], selected: SPEAKER_PHONE
D/FlutterWebRTCPlugin(25092): Starting the audio manager...
D/FlutterWebRTCPlugin(25092): onAudioManagerDevicesChanged: [SPEAKER_PHONE, EARPIECE], selected: SPEAKER_PHONE

Conclusion:
It seems that the audio manager is being started on app launch, instead of on session launch, which is putting the app and the device into the in-call state.

**To Reproduce**
1) Create a new flutter project (flutter create .)
2) Launch app. Adjust volume on device. Because no media is playing, Android will default to adjusting the ringing volume (Correct).
3) Add flutter_webrtc to app.yaml
4) Follow steps of Android integration steps as described in readme
5) Launch the app again. Adjust volume on device. In-Call volume is being adjusted. Android sees the app as being in-call (Incorrect).

**Expected behavior**
The app/plugin should only put the device in in-call state during an active webrtc session.

**Platform information**

* **Flutter version**:
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-ZA)
    • Flutter version 1.12.13+hotfix.8 at /Users/sociosoft/Library/Flutter
    • Framework revision 0b8abb4724 (13 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sociosoft/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • SM A507FN          • R58M906VCQT                              • android-arm64 • Android 9 (API 28)
    • Sociosoft’s iPhone • 733670b2c39e1adfb9a4747c571fc34a8ff609cf • ios           • iOS 11.2.1

• No issues found!

* **Plugin version**: Master, commit: 7fdf8369e8f99ed47fa7d659f15e19526b74c9c1
flutter_webrtc:
    git:
      url: https://github.com/cloudwebrtc/flutter-webrtc
      ref: master

* **OS**: 
Android
* **OS version**: 
Android 9 (only tested on this)

**Comment by Sociosoftware** [comment]
I have resolved this by switching to the stable branch instead. I'd also like to note that this doesn't affect the sessions in any way.

Regardless, I would like to report this as it's something that shouldn't go into a future stable build.

**Comment by Sociosoftware** [comment]
The reason I was using master is because of this issue : #168 
It was fixed with #188 that is in master, but not yet in stable.

By switching to stable I can build successfully on Android, which overcomes the in-call bug mentioned in this report. However, the current stable branch does not build in iOS.

**Comment by Sociosoftware** [comment]
Why was this closed? It is an active issue in the master branch as of 7fdf836.

**Comment by huulbaek** [comment]
I'm pretty sure I experience this behaviour on 0.2.6 too. When I open app the volume controls are shifted to in-call right away and stays that way.

**Comment by huulbaek** [comment]
Is there any way to start audiomanager manually instead? It seems that the plugin is initialising it right away even if plugin is not active.

Or maybe start it without changing the option to ```MODE_IN_COMMUNICATION``` until there is communication active.

**Comment by huulbaek** [comment]
In my [fork](https://github.com/huulbaek/flutter-webrtc) I added start and stop of audiomanager instead of starting it right away. This fixed the issue for me.

**Comment by cloudwebrtc** [comment]
This problem has been fixed in 0.2.6, it may be that an error occurred during my merge, and I will fix it.
https://github.com/cloudwebrtc/flutter-webrtc/blob/6aaaa0e134a23db702332bf5e48eac9a318a40f0/android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java#L736

**Comment by ycherniavskyi** [comment]
@cloudwebrtc to close several issues within one commit message, by [GitHub rules](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords), you need to set a special closing keyword before each issue number 😊.
