### ISSUE TITLE
can anyone help me making by small video of flutter webrtc?

### ISSUE THREAD

**Issue by kaushiklad55** [cloudwebrtc/flutter-webrtc#199]
i m trying to implement WebRTC in flutter with my own WebRTC server ...

i read plugin code and example code cant understand anything how it start and where is go ???

give me small explanation ...

**Comment by cloudwebrtc** [comment]
The plug-in is completely encapsulated according to the WebRTC API, so when you read the webrtc standard API, I am sure you can call this plug-in, or refer to flutter-webrtc-demo
