### ISSUE TITLE
flutter video render idea?

### ISSUE THREAD

**Issue by kaushiklad55** [cloudwebrtc/flutter-webrtc#200]
as of i know flutter can call native method and send argument as String and return result as string obj 

but when video call futures come ...i need to pass local video and remote video to flutter widget ..so how can i archive this ? any concept or guide ?

in this sample u really pass stream to flutter widget from native ??

**Comment by cloudwebrtc** [comment]
The current plug-in uses texture to render video, and is not really playing a video stream. Instead, display RGB data frame by frame to the Texture Widget
