### ISSUE TITLE
Problem while creating app release with v 0.2.7 and flutter v1.12.13+hotfix.8

### ISSUE THREAD

**Issue by ZatacaSystems** [cloudwebrtc/flutter-webrtc#208]
**Describe the bug**
Hello
I have a problem with version 0.2.7 and flutter version v1.12.13+hotfix.8
I create de apk and when I install it it launches and then closes (crashes)

**To Reproduce**
flutter build apk --release, install and run

**Expected behavior**
The app should work

**Platform information**

* **Flutter version**: v1.12.13+hotfix.8
* **Plugin version**:0.2.7

**Comment by ac130kz** [comment]
https://github.com/cloudwebrtc/flutter-webrtc/issues/205#issuecomment-601541102

this answer helped me to resolve the issue

**Comment by ZatacaSystems** [comment]
@ac130kz I have already added proguard to my project and I the apps that I generate still crash when I install and run them :(

**Comment by ZatacaSystems** [comment]
I really need help with this, I have added proguard and this stills crashes, Is it possible that the problem is with the new R8 proguard for flutter?

**Comment by ycherniavskyi** [comment]
@ZatacaSystems, do you have this issue so far?
I just commit to the master branch library level ProGuard configuration file (#243). Could you please try to rebuild you app with git version of `flutter-webrtc`?

**Comment by ZatacaSystems** [comment]
@ycherniavskyi yes, sorry I forgot to close this. I was miswriting the name of the proguard file ^^' it works like a charm when you do the proguard steps the right way 👍
