### ISSUE TITLE
Video stream do not play in iOS when using flutter-webrtc with pion

### ISSUE THREAD

**Issue by zjiang91** [cloudwebrtc/flutter-webrtc#212]
Hi,

I am using pion with flutter Webrtc and I found my video only play in Android but not in iOS. I suspect it is the same issue with https://github.com/pion/example-webrtc-applications/issues/3.

But I tried the suggestions here: https://github.com/pion/webrtc/issues/716. It is not working.

Any suggestions on how to figure out why? Also, I am not able to find any logging in iOS simulator while Android can show something like I/org.webrtc.Logging(30820). Therefore, I don't know why iOS cannot play the video stream.

**Comment by cloudwebrtc** [comment]
@zjiang91 The connection between the mobile terminal and pion is generally caused by the inconsistent payload type.

**Comment by zjiang91** [comment]
ty so much for the reply, I do have a few questions for this:

1. In the pion/example-webrtc-applications#3, you mentioned you  found the issue by "the webrtc log shows that the decoder could not find the keyframe" in iOS, where did you see the log? (I cannot see anything, do I have to recompile GoogleWeRTC framework to enable some logging?) I just want t o confirm this is the same issue with you mentioned.
2. I tried to fix it by registering the VP8 codec in pion `m.RegisterCodec(webrtc.NewRTPVP8Codec(100, 90000))`, while your example in sfu is modifying the rtp to use 96: https://github.com/cloudwebrtc/example-webrtc-applications/commit/71261f121ca9de65f346d638422e17644281b3ec. My change to let the iOS client and pion client to both use payload type = 100 seems a wrong way. What am I missing here? Isn't the solution just set the two sides to use the same payload type, or my understanding is wrong?

Thanks again for helping.

**Comment by zjiang91** [comment]
I finally found the problem is due to I run the application in iOS emulator. It works fine in iOS real device. Perhpas due to the GoogleWebRTC not built with x86 by default? (Just a suspect)

Anyway, ty. And it would be nice if people can share how to debug.
