### ISSUE TITLE
Master branch android build error

### ISSUE THREAD

**Issue by rostopira** [cloudwebrtc/flutter-webrtc#24]
Missing method `maybeRequestPermissionsOnHostResume` implementation in master branch:

https://github.com/cloudwebrtc/flutter-webrtc/blob/master/android/src/main/java/com/cloudwebrtc/webrtc/utils/PermissionUtils.java#L105

**Comment by rostopira** [comment]
Master seems to be completely broken for iOS as well

**Comment by cloudwebrtc** [comment]
@rostopira 
I have fixed this issue.
Later, maybe we can use the a flutter plugin to complete the permission request, which will make the native code simpler.

**Comment by rostopira** [comment]
@cloudwebrtc you could possible use `Application.ActivityLifecycleCallbacks` for that, but I personally don't think this feature makes any sense. I'm using WebRTC in background, but that's edge case
BTW, I've tested this plugin on API level 17, and it works fine
