### ISSUE TITLE
Cant find a well documents

### ISSUE THREAD

**Issue by muhammadwafa** [cloudwebrtc/flutter-webrtc#247]
Will this package maintained for a long time as free??
If yes could you please help me where can I find the documentation?

**Comment by ycherniavskyi** [comment]
For now, source code is the documentation.
But in general, the code of this plugin is Google WebRTC library, so all negotiation with the plugin is almost the same as in a browser.

**Comment by muhammadwafa** [comment]
You mean this package works as an embedded web app with flutter ?

**Comment by ycherniavskyi** [comment]
Um, no. I mean, that conception is the same.

**Comment by darwin-morocho** [comment]
Yes flutter-webrtc works very similar as browser

**Comment by ycherniavskyi** [comment]
@muhammadwafa, for now, I am closing this issue because I don't see how anybody could help you with this. Unfortunately, `flutter-webrtc` has no good no bag documentation yet.
