### ISSUE TITLE
 Screen Capture

### ISSUE THREAD

**Issue by startupgurukul** [cloudwebrtc/flutter-webrtc#26]
Hey, Thanks for the plugin. 

This issue is about implementing  Screen Capture, I did notice it is on the todo list and there is already a bit of implementation with MediaProjection on android side, can you let us know the status if its ready to use

**Comment by cloudwebrtc** [comment]
Not yet available, Android has completed part of it, and it also needs to complete the getDisplayMedia method in the dart layer and some unit tests.

**Comment by startupgurukul** [comment]
Looking forward. Once again thanks for the great plugin

**Comment by cloudwebrtc** [comment]
I added an RPScreenRecorder to iOS, I can get the captured CMSampleBufferRef from [FlutterRPScreenRecorder.m#L62](https://github.com/cloudwebrtc/flutter-webrtc/blob/master/ios/Classes/FlutterRPScreenRecorder.m#L62), but I can't render it, I don't find any way.   :(
Can someone help me?

**Comment by cloudwebrtc** [comment]
Done the ScreenCapture feature.
