### ISSUE TITLE
proper idea to use webrtc

### ISSUE THREAD

**Issue by harshapulikollu** [cloudwebrtc/flutter-webrtc#32]
I'm having a p2p chat app in flutter using firebase firestore. I want to have p2p video call in that app when user user clicks video call button they both should able to make video call. but I'm unable to get started, as I can't understand signalling server, ice, turn and other things.🤯🤯 can you please elaborate the things that how can I start using firestore to make video call feature possible in app. just using the plugin will make it possible or what I have to do!

**Comment by cloudwebrtc** [comment]
You can use sample code in https://github.com/cloudwebrtc/flutter-webrtc/issues/18#issuecomment-432381115, other guys have implemented video calls based on firebase with this plug-in.
