### ISSUE TITLE
Support Data Channel

### ISSUE THREAD

**Issue by cloudwebrtc** [cloudwebrtc/flutter-webrtc#34]
Implement data channel and sample.

**Comment by rostopira** [comment]
Data channel is working perfectly already, for me at least
You want example in demo repo?

**Comment by cloudwebrtc** [comment]
Yes, a loopback example, the data channel has not been tested and may need to be optimized.

**Comment by rostopira** [comment]
I can implement sample, as soon as I'm done and dusted with android render hell

**Comment by cloudwebrtc** [comment]
Verified, working fine.
