### ISSUE TITLE
Support volume control for recorded audio

### ISSUE THREAD

**Issue by aryzhov** [cloudwebrtc/flutter-webrtc#39]
Since webrtc encapsulates audio capture, it's desirable to control the volume (or gain) of the recorded audio track. I propose to add method `MediaStreamTrack.setVolume(double volume)`, which would apply a gain multiplier to an audio track. The underlying WebRTC API has the corresponding volume control methods, which are platform-specific and exist for both iOS and Android.

**Comment by rostopira** [comment]
LGTM, I will run some tests before merge

**Comment by rostopira** [comment]
Yep, it works. But it's increasing playback volume, not capturer sensitivity
And it's actually gain, not volume, it's even stated in [java doc](https://webrtc.googlesource.com/src/+/master/sdk/android/api/org/webrtc/AudioTrack.java#19)

```java
/** Sets the volume for the underlying MediaSource. Volume is a gain value in the range
--
  | *  0 to 10.
  | */
  | public void setVolume(double volume) {
  | nativeSetVolume(getNativeAudioTrack(), volume);
  | }
```

Maybe will be better to rename method to `setGain`?

**Comment by cloudwebrtc** [comment]
I think named ```setVolume ``` is fine, there is no ambiguity for a single AudioTrack.

**Comment by rostopira** [comment]
@cloudwebrtc okay, I will merge then
