### ISSUE TITLE
Widget Capture

### ISSUE THREAD

**Issue by codename47** [cloudwebrtc/flutter-webrtc#44]
Thank you for awesome library.

Any possibilities implement to send widget's video.

**Comment by cloudwebrtc** [comment]
This may be to capture the widget and convert it to RGB data and send it to VideoSourceTrack.

Find an example that can be referenced, capture screen from flutter:
https://github.com/zhaoya188/flutter_app/blob/master/lib/screenshot.dart

**Comment by cloudwebrtc** [comment]
Not part of the plugin features.

**Comment by rahmanrezaee** [comment]
Does any one finds a solution??
