### ISSUE TITLE
Switch audio output from phone audio to speaker audio.

### ISSUE THREAD

**Issue by gbarnett** [cloudwebrtc/flutter-webrtc#45]
Hi, 

I have greatly appreciated this framework. Thank you. 

I'm wondering if anyone would know how to switch the audio output to speakerphone instead of phone audio; currently, during a video chat, the audio from the video is played through the phone's ear speaker and not through the main speaker or the 'speakerphone.' 

I think this would be a necessary functionality for video calls on mobile.

**Comment by rostopira** [comment]
Yeah, we are aware of this issue
But we decided that's audio routing, proximity sensor handling and keeping screen on while in call is way too much for a single plugin, so we only do things that related to WebRTC core directly and can't be done without modifying this pluging source
Official example (AppRTC) contains this features, but not the core
There are a separate plugin you can use for this purpose https://github.com/cloudwebrtc/flutter-incall-manager

**Comment by Jartz** [comment]
Hi; I have problem with plugin incallManager version Flutter SDK >2.0.0;  how could I fix it? 
Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
thanks for your help

**Comment by rostopira** [comment]
@Jartz use original master instead of work, it was update recently: https://github.com/kangshaojun/flutter-incall-manager

**Comment by dnsprado** [comment]
Hi guys. I solved this problem in the past using flutter incall lib. However they did not update it for Dart 2.12 nullsafety. Are there any other alternative way of solving this issue?

Thanks!

**Comment by bella0x0** [comment]
> 

having the same issue, can you please update if you solved this

**Comment by dnsprado** [comment]
> having the same issue, can you please update if you solved this
> 
> > Hi guys. I solved this problem in the past using flutter incall lib. However, they did not update it for Dart 2.12 null safety. Are there any other alternative ways of solving this issue?
> > Thanks!

Hi bella0x0, I still didn't solve it. I am waiting for some collaborator to give us some guidance. @rostopira can you help us?
