### ISSUE TITLE
compileOptions breaks the apk.

### ISSUE THREAD

**Issue by Hanshi** [cloudwebrtc/flutter-webrtc#48]
I added these compileOptions as suggested in the app level build.gradle file to make it build in my Android Studio.
But the .apk I build will crash on my android test phone.
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
Any solution?

**Comment by rostopira** [comment]
LogCat?
Pub or master branch? 
Have you tried to set NDK to armv7 only?

**Comment by Hanshi** [comment]
Master branch. 
How to set NDK to armv7 only? I think our andoird phones are mostly armv8 now.

**Comment by rostopira** [comment]
You think it's OK to ignore questions?
Logcat or steps to reproduce
Is it so hard?

**Comment by rostopira** [comment]
Close as CNR
