### ISSUE TITLE
Something is hanging in the memory after the completion of the video call

### ISSUE THREAD

**Issue by kostasoft** [cloudwebrtc/flutter-webrtc#51]
After the completion of the call, the following message appears in the log at intervals of a second or two:
`I/org.webrtc.Logging(13858): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.`
My Dispose method:
```
@override
  void dispose() {
    if (_localStream != null) {
      if (_peerConnection != null)
        _peerConnection.removeStream(_localStream);
      _localStream.dispose().then((value){
        _localStream = null;
      });
    }
    super.dispose();
    print("+++ CallScreen Dispose +++");
  }
```
What did I forget?

**Comment by rostopira** [comment]
Oh
That's my fault
I will fix it tomorrow

**Comment by kostasoft** [comment]
I could not understand a couple of hours, but as I wrote this post, I immediately understood:
```
    _localRenderer.dispose();
    _remoteRenderer.dispose();
```
I think the topic can be closed. If you do not add anything, tomorrow I will close ...
Sorry for the stupid question ...

**Comment by rostopira** [comment]
I was actually going to add auto dispose for renders
