### ISSUE TITLE
Rendering fails when video width < 720

### ISSUE THREAD

**Issue by anewgate** [cloudwebrtc/flutter-webrtc#56]
Hi dear.
I wonder why this has changed.
If it changes like this, no video will be output.
After that, however, the video is output again.
Please answer me. ;(

[envoronment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

[mediaconstraint code]
    Map<String, dynamic> mediaConstraints = {
      'audio': true,
      'video': {
        'mandatory': {
          'minWidth': '640',
          'minHeight': '480',
          'minFrameRate': 30,
        },
        'facingMode': 'environment',
        'optional': [],
      }
    };
    try {
      await navigator.getUserMedia(mediaConstraints).then((stream) async {
        _localStream = stream;
      });
    } catch (e) {
      debugPrint(e.toString());
    }

[create peerconnection]
  Future<Null> goCreatePeerConnection() async {
    _pc = await createPeerConnection(_iceServers, _config);   

    _pc.onIceCandidate = (candidate) {      
      RTCIceCandidate newCandidate;
      if(candidate == null) {
        debugPrint('candidate is null');
      } else {
        newCandidate = new RTCIceCandidate(
          candidate.candidate, 
          candidate.sdpMid, 
          candidate.sdpMlineIndex);
      }
      sendCandidate(newCandidate);
    };

    **_pc.addStream(_localStream);  <---- I think this code is problem.**
  }

[rtc_video_view.dart]
...
  initialize() async {
    final Map<dynamic, dynamic> response =
        await _channel.invokeMethod('createVideoRenderer', {});
    _textureId = response['textureId'];
    _eventSubscription = _eventChannelFor(_textureId)
        .receiveBroadcastStream()
        .listen(eventListener, onError: errorListener);
    _eventSubscription.onData((dynamic data) {
      debugPrint('--=-=-=-=-=-eventSubscription data:$data');
    });
  }
...

[console log]
flutter: --=-=-=-=-=-eventSubscription data:{id: 0, event: didTextureChangeVideoSize, width: 480.0, height: 640.0}
flutter: --=-=-=-=-=-eventSubscription data:{event: didTextureChangeRotation, id: 0, rotation: 90}
**flutter: --=-=-=-=-=-eventSubscription data:{id: 0, event: didTextureChangeVideoSize, width: 360.0, height: 480.0}**  <----- This change
flutter: --=-=-=-=-=-eventSubscription data:{id: 0, event: didTextureChangeVideoSize, width: 480.0, height: 640.0}

**Comment by cloudwebrtc** [comment]
Thank you for your detailed bug description, which can be a tricky bug, and it's not yet a bug in webrtc rendering or flutter texture. The problem occurs when the video size of the same texture changes, which causes the video to sometimes show up and stop output. I will continue to try to solve it.

**Comment by anewgate** [comment]
Thank you for your kind and detailed reply.
I will keep trying.

**Comment by rostopira** [comment]
Attempt to fix that by replacing `FlutterTexture` with `FlutterPlatformView` lies here
https://github.com/cloudwebrtc/flutter-webrtc/tree/metal_experiment

**Comment by cloudwebrtc** [comment]
@rostopira @LinusU @anewgate 
This change submitted https://github.com/cloudwebrtc/flutter-webrtc/commit/83f690b03888e011695c9b160a3b07b3559b017d may have fixed the issue and https://github.com/cloudwebrtc/flutter-webrtc/issues/26 that the Screen Frame cannot display.
It may take several test confirmations before the issue can be closed.

The reason is that CVOpenGLESTextureCacheCreateTextureFromImage in ios_external_texture_gl.mm cannot create TextureCache and return to -6683. I refer to https://developer.apple.com/library/archive/qa/qa1781/_index.html for patches.

**Comment by rostopira** [comment]
iPad (2018) with iOS 12.0: works

**Comment by cloudwebrtc** [comment]
I verified on iPhone 8 and iPhone X and it worked fine, so close the issue now.
