### ISSUE TITLE
Cant get SessionDescription to work on another JavaScript Side

### ISSUE THREAD

**Issue by CodeStrings** [cloudwebrtc/flutter-webrtc#57]
I try to build a Electron Application but I cant parse the Session Description or the RemoteDescription. 
'DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription.'

Code:
var sdp = { "type": data.descriptiontype, "description": data.descriptionsdp };
  console.log(sdp)
  peerConnection.setRemoteDescription(sdp)

**Comment by cloudwebrtc** [comment]
Not a question about the flutter-webrtc plugin?

**Comment by CodeStrings** [comment]
In someway it has to be compatible with „original“ WebRTC

**Comment by cloudwebrtc** [comment]
You need to provide a log to help solve the problem.
