### ISSUE TITLE
请教下，能否实现一对多？

### ISSUE THREAD

**Issue by Leadrive** [cloudwebrtc/flutter-webrtc#59]
请教下一对多如何实现？
谢谢！

**Comment by cloudwebrtc** [comment]
多人比较麻烦，用mesh p2p多pc方式或部署SFU，需要较多修改。

**Comment by Leadrive** [comment]
@cloudwebrtc  新年好，一对多还是最实用的功能，希望老大能抽点时间规划实现，我们帮忙测试完善，谢谢。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Leadrive** [comment]
期待ing...

**Comment by cloudwebrtc** [comment]
问题合并到 https://github.com/cloudwebrtc/flutter-webrtc/issues/62
