### ISSUE TITLE
Backend server

### ISSUE THREAD

**Issue by gedw99** [cloudwebrtc/flutter-webrtc#6]
Can you tell me the backend and codecs ?

Thanks for this great GUI

**Comment by gedw99** [comment]
Wow that's really great.

If you need help I am happy to help as I have worked on a golang webrtc
server previously

**Comment by cloudwebrtc** [comment]
Our flutter-webrtc-server only shows the basic use of WebRTC. Other SFU/MCUs can be used in complex scenarios. Any WebRTC-compatible server can be used. I think the golang server also works very well.

**Comment by gedw99** [comment]
Do you have a golang server implementation too ?

**Comment by cloudwebrtc** [comment]
No, our open source project only has a client, but we already have MCU/SFU developed in C++, but it is not open source. We have some experience in SFU/MCU development. If you need help, we will be happy to help.

**Comment by gedw99** [comment]
Thanks for the offer. I think the golang version is all good.

**Comment by johnjelinek** [comment]
Which golang server so you recommend?
