### ISSUE TITLE
One-to-many example with pions/webrtc

### ISSUE THREAD

**Issue by Leadrive** [cloudwebrtc/flutter-webrtc#62]
https://github.com/pions/webrtc

Pion WebRTC aims to solve all that! Built in native Go you should be able to send and receive media and text from anywhere with minimal headache. These are the design principals that drive Pion WebRTC and hopefully convince you it is worth a try.

**Comment by cloudwebrtc** [comment]
Yes, this is the issue of a few months ago on the pions. But I don't understand golang development and need someone to help.

**Comment by gedw99** [comment]
@cloudwebrtc i know golang and flutter. 
Tell me what you need and i can do it and show you also ?

**Comment by cloudwebrtc** [comment]
@gedw99 Maybe we can use flutter webrtc to connect pions/webrtc to implement a one-to-one or video conference or live broadcast example.

**Comment by cloudwebrtc** [comment]
@gedw99 I created an example of flutter for sfu-ws here [sfu-ws/flutter](https://github.com/cloudwebrtc/pions-webrtc/tree/master/examples/sfu-ws/flutter), I did some simple tests, Publisher is works.

**Comment by cloudwebrtc** [comment]
@gedw99 @Leadrive 
The new demo has been moved to [sfu-ws/flutter](https://github.com/cloudwebrtc/example-webrtc-applications/tree/master/sfu-ws/flutter), and I have done a publisher/subscriber test that works fine.

**Comment by lovemoon** [comment]
hi
How I can use flutter Webrtc with
https://github.com/muaz-khan/WebRTC-Experiment/tree/master/broadcast

**Comment by cloudwebrtc** [comment]
@ghost @Leadrive 
I and @adwpc have completed the multi-party video call demo between ion SFU and Flutter, so close this issue.
https://github.com/pion/ion

**Comment by rezadevelopers2** [comment]
hello 
[loudwebrtc/example-webrtc-applications/sfu-ws/flutter](https://github.com/cloudwebrtc/example-webrtc-applications/tree/master/sfu-ws/flutter),
not found url

**Comment by cloudwebrtc** [comment]
You can refer to this link
https://github.com/pion/example-webrtc-applications/tree/master/sfu-ws

**Comment by rezadevelopers2** [comment]
Hi, I tested this code, when the third person enters, it is not added to the list. Apparently, the code has a problem. Can you help me make a group call?

**Comment by lxl518000** [comment]
> 你好，我测试了这段代码，当第三人进入时，它没有被添加到列表中。显然，代码有问题。你能帮我打个群呼吗？

same issue 
could you please check it @cloudwebrtc
