### ISSUE TITLE
Getting access to raw audio data

### ISSUE THREAD

**Issue by solderneer** [cloudwebrtc/flutter-webrtc#63]
Just wondering if there is anyway to intercept the audio data as a raw data stream of sorts. Need raw audio data so that some signal processing (silence removal) can be done. Thanks!

**Comment by rostopira** [comment]
Yeah, it's definitely possible
I've did that for recording to file
In Android part check out recorder and audio interceptor classes

**Comment by solderneer** [comment]
Ah, alright thanks, I'll close the issue then!.
