### ISSUE TITLE
是否支持鏡像？

### ISSUE THREAD

**Issue by dexterliu1214** [cloudwebrtc/flutter-webrtc#64]

**Comment by cloudwebrtc** [comment]
暂未实现镜像显示，您可以尝试在Flutter上嵌套Transform来做水平翻转。

**Comment by cloudwebrtc** [comment]
已经在 https://github.com/cloudwebrtc/flutter-webrtc/commit/ffde813d06772f888b2b8b4bb41d677ca8c1cb2d 增加mirror功能.
