### ISSUE TITLE
Local MediaStream drops out on iPhone 6

### ISSUE THREAD

**Issue by LinusU** [cloudwebrtc/flutter-webrtc#66]
This can be seen in the example app, after connecting a call the local video on the iPhone 6 (and the remote video on the other device) disappears after ~1-2 seconds. Sometimes it comes back after a while, but then it also disappears a while after that...

Happy to provide any more information you might need!

**Comment by rostopira** [comment]
Duplicate of #56 
I'm working on it currently

**Comment by LinusU** [comment]
Sorry, that's great to hear though! Let me know if I can help in any way 🙌

**Comment by rostopira** [comment]
Check out metal_experiment branch
Test
Debug
Fix
PR
??????? 
PROFIT
