### ISSUE TITLE
Getting notified when switching camera

### ISSUE THREAD

**Issue by LinusU** [cloudwebrtc/flutter-webrtc#68]
I'm trying to have my local video stream mirrored when using the front-facing camera, but not mirrored when using the back camera.

My current code looks something like this:

```dart
_localStream.getVideoTracks()[0].switchCamera();
_renderer.mirror = !_renderer.mirror;
```

The problem is that `switchCamera` takes ~1s, but setting the `mirror` property is instant. It thus creates a bit of an awkward UI experience...

Is it possible to get a callback when the camera is actually switched, so that I can time setting `mirror` at the exact same time?

**Comment by na2axl** [comment]
This will be very useful since I'm searching for the same feature

**Comment by rostopira** [comment]
Well, this one is pretty easy to implement
Okay, let me just do it ;)

**Comment by rostopira** [comment]
Please somebody test it

**Comment by LinusU** [comment]
@rostopira just tested it and works great! Thanks for the quick implementation!

Sometimes I'm seeing one or two frames that's not mirrored after switching, but much better than before...

Thanks! 🚀

**Comment by VictorUvarov** [comment]
How are getting the local renderer to mirror? I don't see this functionality anymore.
<img width="639" alt="Screenshot 2023-07-27 at 10 25 47 AM" src="https://github.com/flutter-webrtc/flutter-webrtc/assets/35702719/0cd123f4-0747-422a-9056-5fcdc279737a">

**Comment by VictorUvarov** [comment]
> How are getting the local renderer to mirror? I don't see this functionality anymore. <img alt="Screenshot 2023-07-27 at 10 25 47 AM" width="639" src="https://user-images.githubusercontent.com/35702719/256616941-0cd123f4-0747-422a-9056-5fcdc279737a.png">

Ended up just flipping it in the UI code
```dart
Transform(
                      alignment: Alignment.center,
                      transform:
                          _mirrorLocalRenderer ? Matrix4.rotationY(3.14159) : Matrix4.identity(),
                      child: ClipRRect(
                        borderRadius: const BorderRadius.all(Radius.circular(8)),
                        child: RTCVideoView(
                          _localRenderer!,
                          objectFit: RTCVideoViewObjectFit.RTCVideoViewObjectFitCover,
                          filterQuality: FilterQuality.medium,
                        ),
                      ),
                    )
```

**Comment by cloudwebrtc** [comment]
```dart
RTCVideoView(_localRenderer, mirror: true);
```
