### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by SnowcatSVK** [cloudwebrtc/flutter-webrtc#7]
Hello,
While trying out your example app I have ran into a problem. On Android i get the UnsatisfiedLinkError
whole stacktrace: 
```
com.cloudwebrtc.webrtcexample E/org.webrtc.Logging: NativeLibrary: Failed to load native library: jingle_peerconnection_so
    NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.cloudwebrtc.webrtcexample-zASNzno6_zbJwbicSb0Dpg==/base.apk"],nativeLibraryDirectories=[/data/app/com.cloudwebrtc.webrtcexample-zASNzno6_zbJwbicSb0Dpg==/lib/x86_64, /system/fake-libs64, /data/app/com.cloudwebrtc.webrtcexample-zASNzno6_zbJwbicSb0Dpg==/base.apk!/lib/x86_64, /system/lib64]]] couldn't find "libjingle_peerconnection_so.so"
```
The app works great on iOS, but I cant get around this on Android. Every suggestion would help.

**Comment by kangshaojun** [comment]
you need import android/libs/*.jar files

**Comment by SnowcatSVK** [comment]
import exactly how? it is in the build.gradle of webrtc module if that is what you mean

**Comment by cloudwebrtc** [comment]
@SnowcatSVK 
From the log analysis, does not support the x86_64 architecture so, you are using the ARM architecture?
If not, you can apply doc/patchs/m63_patch_for_flutter_webrtc_plugin_v0.patch to recompile webrtc M63 to support x86_64 architecture.

**Comment by SnowcatSVK** [comment]
@cloudwebrtc first i tried it on x86_64 emulator and when i saw the logs i have tried it on pixel 2, where i get the same error, only there it said it couldnt find armeabi_v8a, so then i guess i would have to recompile it for both x86_64 and armeabi_v8a?

**Comment by cloudwebrtc** [comment]
@SnowcatSVK Yes, you can try to recompile it for both x86_64 and armeabi_v8a(arm64).
Normally, if you run the Android native app, armv7 library can run in the arm64 platform, and x86 library can run in x86_64 architecture. As far as I know flutter is still unable to run in x86 or x86_64 even arm64 platform, you need to exclude the errors caused by it.

**Comment by SnowcatSVK** [comment]
ok then, i will try to recompile it and see if that helps, thank you for your time

**Comment by gedw99** [comment]
Could some notes about this eventually be added to the readme ? Ir even better a make file to see how to do this sort of ISA architecture shuffling ?
Just because its quite complex to know what to do on android to get it working in Sim and on real device.

**Comment by cloudwebrtc** [comment]
Ok, I will update README.md and add x86_64 and arm64 architecture to the next commit.

**Comment by cloudwebrtc** [comment]
@SnowcatSVK We have recompiled this native sdk, support armv7, arm64, x86, x86_64 on android, you can view the latest commit.

**Comment by SnowcatSVK** [comment]
@cloudwebrtc Just tested it out and everything works rather nicely, thank you very much for your help
