### ISSUE TITLE
i try to run pod install but this question already

### ISSUE THREAD

**Issue by adminparry** [cloudwebrtc/flutter-webrtc#74]
Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "GoogleWebRTC":
      In Podfile:
        flutter_webrtc (from `Pods/.symlinks/plugins/flutter_webrtc/ios`) was resolved to 0.0.1, which depends on
          GoogleWebRTC (= 1.1.26791)

    None of your spec sources contain a spec satisfying the dependency: `GoogleWebRTC (= 1.1.26791)`.

**Comment by rostopira** [comment]
Have you tried to run `pod update`?

**Comment by adminparry** [comment]
> Have you tried to run `pod update`?

yes, and run pod search GoogleWebRTC is find

**Comment by rostopira** [comment]
Try to change version in podspec to 1.1.27564

**Comment by LinusU** [comment]
I've seen some similar problems as well, I _think_ that it might be because the version in our podspec is never changed, even though the podspec itself and the plugin version is. This causes cocoapods to be confused when the `flutter_webrtc` is the same but the dependency on `GoogleWebRTC` has changed.

A quick fix for you is probably to remove your `ios/Podfile.lock` and then run `pod install` in the `ios` folder to regenerate it.

A fix we could do in this repo _could_ be to bump the version in the podspec either with every release of the plugin, or whenever we make changes to the podspec...

**Comment by rostopira** [comment]
@LinusU I'm updating deps on android and ios from time to time
We could set not exact version in podspec, but that may cause issues, because WebRTC team doesn't always keep new versions backward compatible (they removed constants just about 5 versions ago, and plugin couldn't build at all)

**Comment by LinusU** [comment]
I _think_ that bumping this version:

https://github.com/cloudwebrtc/flutter-webrtc/blob/adaf1fa2011790677313286099bfd991edcf35aa/ios/flutter_webrtc.podspec#L6

Every time we modify that file should be enough.

I _think_ that the problem is that cocoapods doesn't see it as a new version, and thus gets confused that the dependencies have changed.

**Comment by adminparry** [comment]
i try to remove version is work it

#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'flutter_webrtc'
  s.version          = '0.0.1'
  s.summary          = 'Flutter WebRTC plugin for iOS/Android.'
  s.description      = <<-DESC
A new flutter plugin project.
                       DESC
  s.homepage         = 'http://www.cloudwebrtc.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.dependency 'libyuv-iOS'
  s.dependency 'GoogleWebRTC'
  s.ios.deployment_target = '9.0'
  s.static_framework = true
end

**Comment by Mohamed-Fakhry** [comment]
**Describe the bug**
Hi dear.
when flutter run on iOS that's appear

CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_webrtc` from `.symlinks/plugins/flutter_webrtc/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "flutter_webrtc":
      In Podfile:
        flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`)
    Specs satisfying the `flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`)` dependency were found, but they required a higher minimum deployment target.
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'

Platform iOS

* **Flutter version**
[✓] Flutter (Channel master, v1.6.1-pre.68, on Mac OS X 10.14.4 18E226, locale en-EG)
    • Flutter version 1.6.1-pre.68 at /Users/mohamedfakhry/Documents/flutter
    • Framework revision d5aae54a28 (3 weeks ago), 2019-05-20 23:19:18 -0400
    • Engine revision 301f560bd8
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 b48c8b1d1c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mohamedfakhry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone Xʀ • 6F0029EC-1830-47A8-B6D0-4BCCE91EC006 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

**Plugin version**:
flutter_webrtc: ^0.1.7

**Comment by iPatel007** [comment]
> **Describe the bug**
> Hi dear.
> when flutter run on iOS that's appear
> 
> CocoaPods' output:
> ↳
> Preparing
> Analyzing dependencies
> Inspecting targets to integrate
> Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
> Fetching external sources
> -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
> -> Fetching podspec for `flutter_webrtc` from `.symlinks/plugins/flutter_webrtc/ios`
> -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
> -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
> -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
> -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
> Resolving dependencies of `Podfile`
> [!] CocoaPods could not find compatible versions for pod "flutter_webrtc":
> In Podfile:
> flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`)
> Specs satisfying the `flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`)` dependency were found, but they required a higher minimum deployment target.
> /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
> /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
> 
> Platform iOS
> 
> * **Flutter version**
>   [✓] Flutter (Channel master, v1.6.1-pre.68, on Mac OS X 10.14.4 18E226, locale en-EG)
>   • Flutter version 1.6.1-pre.68 at /Users/mohamedfakhry/Documents/flutter
>   • Framework revision d5aae54a28 (3 weeks ago), 2019-05-20 23:19:18 -0400
>   • Engine revision 301f560bd8
>   • Dart version 2.3.1 (build 2.3.1-dev.0.0 b48c8b1d1c)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> • Android SDK at /Users/mohamedfakhry/Library/Android/sdk
> • Android NDK location not configured (optional; useful for native profiling support)
> • Platform android-28, build-tools 28.0.3
> • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> • All Android licenses accepted.
> 
> [!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
> • Xcode at /Applications/Xcode.app/Contents/Developer
> • Xcode 10.2.1, Build version 10E1001
> ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
> brew update
> brew install --HEAD usbmuxd
> brew link usbmuxd
> brew install --HEAD libimobiledevice
> brew install ideviceinstaller
> ✗ ios-deploy not installed. To install:
> brew install ios-deploy
> • CocoaPods version 1.5.3
> 
> [✓] Android Studio (version 3.4)
> • Android Studio at /Applications/Android Studio.app/Contents
> • Flutter plugin version 35.2.1
> • Dart plugin version 183.6270
> • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [✓] Connected device (1 available)
> • iPhone Xʀ • 6F0029EC-1830-47A8-B6D0-4BCCE91EC006 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
> 
> **Plugin version**:
> flutter_webrtc: ^0.1.7

I think you just have to change deployment target 8.0 to 9.0 from Xocde.

**Comment by CoreyCole** [comment]
> I think you just have to change deployment target 8.0 to 9.0 from Xocde.
This fixed the problem for me in the demo project https://github.com/cloudwebrtc/flutter-webrtc-demo

**Comment by shinriyo** [comment]
Me too.
Actually, I uses

`Pods/Pods.xcodeproj/project.pbxproj`
I replaced
`IPHONEOS_DEPLOYMENT_TARGET = 8.0;`
to
`IPHONEOS_DEPLOYMENT_TARGET = 9.0;`
but...

`ios/Podfile`
`platform :ios, '10.0'`
is better?

**Comment by niyoceles** [comment]
> `ios/Podfile`
> `platform :ios, '10.0'`

ios/Podfile
`platform :ios, '10.0' ` 

is absolutely better on the version `^0.5.8` or up to

This works for me.
```
dependencies:
  flutter_webrtc: ^0.6.5
```
