### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by gedw99** [cloudwebrtc/flutter-webrtc#8]
Could you add the server code link ?
Easier to test

**Comment by kangshaojun** [comment]
please open this url:  https://github.com/cloudwebrtc/flutter-webrtc-server






At 2018-09-04 00:18:06, "gedw99" <notifications@github.com> wrote:


Could you add the server code link ?
Easier to test

**Comment by gedw99** [comment]
hey @kangshaojun 
thanks for the link to the nodejs implementation, but i am looking for a compiled solution.

I saw your c libs in another repo. Are you working that up?

My aim is to get the golang project here working with your flutter implementation. It has SDP and muxer and other nice things the nodejs does not have.
https://github.com/pions/webrtc

Maybe you should have a look also if its aligned with your own goals ?

**Comment by cloudwebrtc** [comment]
@gedw99 I think just need to match the signaling.dart, and offer/answer for pions/webrtc over websockets，workflow like this:
flutter-webrtc (signaling.dart)<----------WS/WSS---------->(signaling.go)pions/webrtc

**Comment by gedw99** [comment]
hey @cloudwebrtc / @kangshaojun 
thanks for looking into this. I am sure the team at pions would be super happy about getting golang and flutter working together. 
For now pions is on a rapid roadmap, but there is enough there now for it to work with Flutter. More things are being done. The only dependency right now is openssl for the DTLS stuff - the golang code is dependent on it. It will be phased out look i think.

If the only change you see in the Flutter code is the signalling then its work putting in a config in your code so it can be tested against the nodejs & the golang version for easy benchmarking.

DO you want me to raise an issue in the main flutter webrtc repo ?

**Comment by cloudwebrtc** [comment]
Ok, you can create new a issue,  we write a demo for pions and working together.

**Comment by gedw99** [comment]
@kangshaojun / @cloudwebrtc 
thanks for getting on board with this. pretty cool.

I think the best way to do this is for you to fork the pions repo to your org and then work on getting it working with Flutter. 
In your forked repo you can make a new examples here: https://github.com/pions/webrtc/tree/master/examples
Maybe call it "flutterserver" for now.

The team at pions will be happy to help i am sure. 
Have you used golang before ?

**Comment by cloudwebrtc** [comment]
@gedw99 We haven't used golang before, but we can learn to use it.  
I have forked pions/webrtc, trying to add flutter demo to it. :)

**Comment by kangshaojun** [comment]
nice.  let's started togethor.

**Comment by gedw99** [comment]
@cloudwebrtc I have been watching the pions project and its getting very close to being usable now from flutter i think. They are working on other advanced stuff like multp party video conferencing a the moment.

Did you introduce yourself on the pions github ??. I am sure they would love to know your thinking about getting flutter and working with it !!

**Comment by cloudwebrtc** [comment]
@gedw99 How to start.
First solve the problems in https://github.com/pions/webrtc/issues/65? 
An simple example of pions <-> flutter-webrtc. Or developing a multiple party video conferencing client for poins SFU? I don't know what pions thinking.

**Comment by kangshaojun** [comment]
@gedw99 Create a Flutter Client and WebApp to connect Pions ？our team can develop  react.js ,  react native,flutter,webrtc mediaserver(sfu/mcu).

**Comment by cloudwebrtc** [comment]
Close here, we will open a new issuse about flutter-webrtc and (SFU/MCU) server interaction.

**Comment by okpatil4u** [comment]
Hi there, thank you for the wonderful work. 
What was the final consensus for the signalling server ? Can we use existing nodejs/golang libraries to implement it ?
Assuming that the signalling server is configured correctly, where do I insert the signalling server url in the example provided ?

**Comment by rostopira** [comment]
@okpatil4u hi! Check out demo app, especially [signaling.dart](https://github.com/cloudwebrtc/flutter-webrtc-demo/blob/master/lib/src/call_sample/signaling.dart)
You can use any signaling server with any API, if you modify this file, for example I use Firebase Real-Time Database to achieve enormous  speed and easy OAuth out of the box.

**Comment by bilalbaz1** [comment]
https://github.com/cloudwebrtc/flutter-webrtc-demo/ I downloaded and run the project from. The project https://demo.cloudwebrtc.com:8086/#/ works in such a local. How can I change this? So, how should I set up my own server?
