### ISSUE TITLE
Security comunication

### ISSUE THREAD

**Issue by magnocasmor** [cloudwebrtc/flutter-webrtc#84]
I'd like to know with this library can set/use security parameters, like SRTP for video and audio

**Comment by rostopira** [comment]
I'm not sure, but I think it's enabled by default
@cloudwebrtc can you answer this?

**Comment by cloudwebrtc** [comment]
@magnocasmor WebRTC does media encryption by default. The native side has the RTCPeerConnectionFactoryOptions.disableEncryption parameter, which can be used to disable SRTP. With the flutter side constraint parameter, you can use the DtlsSrtpKeyAgreement control to select DTLS-SRTP or SRTP-SDES.
```
final Map<String, dynamic> loopbackConstraints = {
      "mandatory": {},
      "optional": [
        {"DtlsSrtpKeyAgreement": true },
      ],
    };
```
If you need flutter side to support disableEncryption, you may need to create a RTCPeerConnectionFactoryOptions parameter to the flutter side.

**Comment by magnocasmor** [comment]
Ok, thanks for answer
