### ISSUE TITLE
[WIP] Support for Flutter Web

### ISSUE THREAD

**Issue by rostopira** [cloudwebrtc/flutter-webrtc#85]
Currently Flutter Web doesn't support embedding non-flutter view
We need `<video>` obviously. Put 👍 on this issue: https://github.com/flutter/flutter/issues/32326
Also, there is no support for plugins right now
This issue will be used to track progress on this issues and implementation progress when they are resolved

**Comment by rostopira** [comment]
Update: PR is coming https://github.com/flutter/flutter/pull/37819

**Comment by rostopira** [comment]
UPD: P2P working - I'm receiving video/audio on Android device from Flutter Web
A lot of work is still has to be done, and I'm still waiting for HtmlView to land on master, but hell yes, it's a great start

**Comment by cloudwebrtc** [comment]
I have completed testing all the plugins for Flutter Web, except switch camera (web can't use the track to switch cameras, must to replace the video track and re-negotiate),  and later use other ways to solve this function.
so close the issue now.

**Comment by maulikchak** [comment]
add Switch camera feature for web @cloudwebrtc

**Comment by aytunch** [comment]
Is web supported at the moment? In pub dev I don't see web listed as a supported problem.

**Comment by cloudwebrtc** [comment]
`flutter-webrtc` fully supports flutter web for all browsers, but since we don't use web plugin to build web support (replaced by import `dart:html` package), use [dart-webrtc](https://github.com/flutter-webrtc/dart-webrtc) to implement web part support.
