### ISSUE TITLE
Is any way to use SIP protocol?

### ISSUE THREAD

**Issue by magnocasmor** [cloudwebrtc/flutter-webrtc#89]
In JS, is possible use WebRTC with SIP library, is any way implemented to do this with this flutter library?

**Comment by cloudwebrtc** [comment]
As far as I know, there is no dart version for sip stack, maybe you can port a dart version via jssip or sipjs, because the two languages have similarities, the other way is to write sip stack plugin, such as resiprocate, sofia-sip.

**Comment by magnocasmor** [comment]
I understood. Thanks for the tip, i will see what i can do with this libs

**Comment by cloudwebrtc** [comment]
@magnocasmor A dart-lang sip stack is coming soon, it will work with flutter-webrtc to become a cross-platform sip client.
https://github.com/cloudwebrtc/dart-sip-ua
