### ISSUE TITLE
Is this project work with Flutter swift?

### ISSUE THREAD

**Issue by ngocphuc1612** [cloudwebrtc/flutter-webrtc#9]

**Comment by cloudwebrtc** [comment]
No, use objective-c for iOS and use java for Android.

**Comment by ngocphuc1612** [comment]
@cloudwebrtc thank for your response, but could you explain why it's not work on swift project?

**Comment by cloudwebrtc** [comment]
@ngocphuc1612 Because WebRTC framework is native to OC, it only needs to be converted to dart API at flutter once.
