### ISSUE TITLE
本地预览播放视频 与 传输视频 分开

### ISSUE THREAD

**Issue by glennWang** [cloudwebrtc/flutter-webrtc#95]
您好，
我想把本地预览播放的视频 与 传输给远程的视频分开，该怎么做 ？

比如：
我本地预览播放的视频是 1080p，但传输给远程是720p，两个视频源来自同一个摄像头。

**Comment by cloudwebrtc** [comment]
我觉得可以通过修改底层代码来修改，公共API里面应该无法做到你的需求
https://github.com/cloudwebrtc/flutter-webrtc/blob/master/android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java#L682
例如在上面的代码行，你可以设置采集分辨率为1080p,  但输出到pc里面的为720p，我不确定是否能正常工作，你可以自己尝试修改。

**Comment by glennWang** [comment]
这个方法有效，非常感谢
