### ISSUE TITLE
如何获取当前正在使用的摄像头名称？

### ISSUE THREAD

**Issue by glennWang** [cloudwebrtc/flutter-webrtc#96]
您好，

我的场景是：

切换摄像头后，能获取到当前正在使用的摄像头，然后：

当使用前置摄像头时，setMirror(true)；

当使用后置摄像头时，setMirror(false)；

**Comment by cloudwebrtc** [comment]
请参考https://github.com/cloudwebrtc/flutter-webrtc/blob/master/lib/rtc_video_view.dart#L52 直接操作RTCVideoRenderer
```dart
RTCVideoRenderer _renderer;
....
_renderer.mirror = true; 
...
```

**Comment by cloudwebrtc** [comment]
可以通过 https://github.com/cloudwebrtc/flutter-webrtc/blob/master/lib/get_user_media.dart#L45 枚举设备，然后通过设置sourceId 来确定前后方的流。

**Comment by felixcloud** [comment]
Hello,

我在flutter-webrtc-demo中调用navigator.getSources();

IOS平台能正常运行，但在Android平台报以下错误：
`Unable to getSources: Unsupported value: com.cloudwebrtc.webrtc.utils.ConstraintsArray@e2f207a`
